### ISSUE TITLE
Mismatch between spec and example on intent naming convention

### ISSUE THREAD

**Issue by tomsugden** [FDC3/Intents#1]
The draft spec describes an upper CamelCase naming convention for intents, but the examples in the `README.md` use lower CamelCase.

Not sure which is prefered, but I assume they should be consistent, unless the intent string is not cAsE-sEnSitIvE.

**Comment by nkolba** [comment]
Thanks for pointing this out Tom!  The readme format is wrong and I'll fix - though whether intents should be case sensitive or not is still an issue open to discussion.

**Comment by espenove** [comment]
This has been fixed
