### ISSUE TITLE
Inconsistent list of global intents

### ISSUE THREAD

**Issue by ColinEberhardt** [FDC3/Intents#7]
The specification draft lists the following initial set of intents:

https://github.com/FDC3/Intents/blob/master/Specification-Draft.MD#initial-set-of-intents

It also introduces the concept of 'standard intents'.

This list differs from the 'global intents' detailed here:

https://github.com/FDC3/Intents/blob/master/src/global%20intents.json

Which list is correct? And what is the correct terminology, global or standard?

**Comment by espenove** [comment]
Hi @ColinEberhardt, small typo in https://github.com/FDC3/Intents/blob/master/Specification-Draft.MD#initial-set-of-intents (**ViewInstument**), any other differences?

I suggest we replace "global" with "standard"

**Comment by ColinEberhardt** [comment]
> Hi @ColinEberhardt, small typo in /Specification-Draft.MD@master#initial-set-of-intents (ViewInstument), any other differences?

My mistake - I managed to misread when comparing the two, I thought 'ViewNews' was missing.

Anyhow, it might be more practical to maintain a single list.
