### ISSUE TITLE
Question - what schema language is being used?

### ISSUE THREAD

**Issue by ColinEberhardt** [FDC3/Intents#8]
The Intent schema is given here:

https://github.com/FDC3/Intents/blob/master/src/Intent.yaml

What schema language is this? And is there any reason why we couldn't use TypeScript as per the API Working Group?

**Comment by espenove** [comment]
Valid question - this is Yaml, for consistency with the other groups, happy to move to TypesScript

**Comment by ColinEberhardt** [comment]
Thanks @espenove - I'm afraid I'm going to be a little pedantic here ...

[YAML](https://en.wikipedia.org/wiki/YAML#Syntax) is a serialization format, which can be used to represent structured data. It isn't a schema (although it could be used to represent one).

In a practical sense I can't take the current Intent 'schema' and use it to validate a document.

To avoid confusion, I'd recommend converting this into a text document.
